name: Run Python Script Daily

on:
  schedule:
    - cron: '0 5 * * *'  # This runs the script at 1 AM EDT (Indiana) daily (5 AM UTC)
  workflow_dispatch:  # This allows manual triggering of the workflow from the GitHub UI

jobs:
  run_script:
    runs-on: ubuntu-latest  # Set up on the latest version of Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Try using Python 3.7 if 3.8 is causing issues

      - name: Install ECCodes (Dependency for pygrib)
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes-dev gfortran  # Install ECCodes and Fortran compilers

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.24 numpy==1.23.5  # Install compatible versions of Cython and NumPy
          pip install --use-pep517 pygrib  # Install pygrib with PEP 517
          pip install -r requirements.txt

      - name: Run the Python script
        run: |
          python ./forecast_script_json.py  # Run your Python script (adjust path if needed)
          
      - name: Commit and push generated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add weatherdata/news_refs/forecasted_weather.json
          git commit -m "Add weather forecast data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
