name: Run Python Script Daily

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5 AM UTC / 1 AM EDT
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install system dependencies (ECCodes, Cython, build tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libeccodes-dev eccodes \
            libjasper-dev libopenjp2-7-dev \
            gfortran libproj-dev proj-data proj-bin \
            libgeos-dev build-essential cython python3-dev

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install pygrib separately with PEP 517
        run: |
          pip install --use-pep517 pygrib

      - name: Install remaining dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the Python script
        run: |
          python ./forecast_script_json.py

      - name: Commit and push generated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add weatherdata/news_refs/forecasted_weather.json
          git commit -m "Add weather forecast data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
