name: Run Python Script Daily

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5 AM UTC / 1 AM EDT
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim-bullseye  # Debian-based, stable and compatible

    steps:
      - name: Install system packages (build tools, eccodes, etc.)
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential gfortran python3-dev \
            libgeos-dev libproj-dev proj-data proj-bin \
            libjasper-dev libopenjp2-7-dev \
            libeccodes-dev eccodes cython

      - name: Install Python packages
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --use-pep517 pygrib
          pip install -r requirements.txt

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run the Python script
        run: |
          python ./forecast_script_json.py

      - name: Commit and push generated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add weatherdata/news_refs/forecasted_weather.json
          git commit -m "Add weather forecast data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
