name: Run Python Script and Save

on:
  schedule:
    - cron: '5 17 * * *'  # Run the script at a specific time (example: UTC 12 PM)
  workflow_dispatch:  # You can trigger it manually as well

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install the Python dependencies
          
      - name: Install ECCodes (Dependency for pygrib)
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes-dev  # Install ECCodes library for pygrib

      - name: Run Python script
        run: |
          python ./forecast_script_json.py  # Adjust the path to your script as needed
          
      - name: Commit and push generated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add weatherdata/news_refs/*
          git commit -m "Add weather forecast data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
