name: Run Python Script Daily

on:
  schedule:
    - cron: '0 5 * * *'  # This runs the script at 1 AM EDT (Indiana) daily (5 AM UTC)
  workflow_dispatch:  # This allows manual triggering of the workflow from the GitHub UI

jobs:
  run_script:
    runs-on: ubuntu-latest  # Set up on the latest version of Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Define the Python version you want to use

      - name: Install ECCodes (Dependency for pygrib)
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes-dev  # Install ECCodes library

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure the dependencies are installed

      - name: Run the Python script
        run: |
          python ./forecast_script_json.py  # Run your python script (adjust path if needed)
          
      - name: Commit and push generated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add weatherdata/news_refs/*
          git commit -m "Add weather forecast data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
