name: Run Python Script Daily

on:
  schedule:
    - cron: '5 17 * * *'  # This means the script will run at 12 PM (UTC) every day.
  # You can also use a specific event to trigger (e.g., push, pull_request, etc.)

jobs:
  run_script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment to run the script.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout your repository code.

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set the Python version to use.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have a requirements.txt

      - name: Run the Python script
        run: |
          python ../forecast_script_json.py  # Replace with the path to your script.
